<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="busdata.aspx.cs" Inherits="BusReservationSystem.busdata" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="stylesheet" href="css/style.css">
    <title>Bus Data</title>
        <style>
        .grid{
    width: 100%; 
    word-wrap:break-word;
    table-layout: fixed;
    font-family: 'Nanum Gothic';
    padding-bottom: 10px;
    font-size: 1.75em;
}
    </style>
</head>
<body>
            <header class="header">

    <a href="#" class="logo"> </i> PurpleBus.Com </a>

     <nav class="navbar">
        <a href="adminhome.aspx">Home</a>
        <a href="addbus.aspx">Add Bus</a>
        <a href="busdata.aspx">View Bus Data</a>
        <a href="viewreservation.aspx">View Reservation</a>
        <a href="viewreview.aspx">View Review</a>
        <a href="customerdata.aspx">View Cutomer Data</a>
        
    </nav>

</header>
    <br><br><br><br><br><br>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="station_no" DataSourceID="SqlDataSource1" GridLines="None" CssClass="grid" ForeColor="#333333">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="station_no" HeaderText="station_no" ReadOnly="True" SortExpression="station_no" />
                    <asp:BoundField DataField="dstation_name" HeaderText="dstation_name" SortExpression="dstation_name" />
                    <asp:BoundField DataField="astation_name" HeaderText="astation_name" SortExpression="astation_name" />
                    <asp:BoundField DataField="dtime" HeaderText="dtime" SortExpression="dtime" />
                    <asp:BoundField DataField="atime" HeaderText="atime" SortExpression="atime" />
                    <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                    <asp:BoundField DataField="bus_no" HeaderText="bus_no" SortExpression="bus_no" />
                    <asp:BoundField DataField="rate" HeaderText="rate" SortExpression="rate" />
                    <asp:BoundField DataField="avail_seat" HeaderText="avail_seat" SortExpression="avail_seat" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" HorizontalAlign="Center" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [avail_bus]" 
                UpdateCommand="UPDATE [avail_bus] Set [dstation_name]=@dstation_name , [astation_name]=@astation_name ,[dtime]=@dtime ,[atime]=@atime ,[date] = @date, [bus_no] = @bus_no,[rate]=@rate,[avail_seat]=@avail_seat" 
                DeleteCommand="Delete From [avail_bus] where [station_no]=@station_no">
            
                </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
